name: Build TWRP 12.1
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build TWRP
        uses: kinguser981/TWRP-Recovery-Builder-2024@main
        with:
          gh_token: ${{ github.token }}
          device_tree_url: ${{ github.server_url }}/${{ github.repository }}
          device_tree_branch: main
          device_path: device/inoi_limited/INOI_A75_Elegance
          device_name: INOI_A75_Elegance
          device_makefile: twrp_INOI_A75_Elegance
          manifest_url: https://github.com/minimal-manifest-twrp/minimal_manifest_twrp_aosp
          manifest_branch: twrp-12.1
          build_target: vendor_boot

